### ISSUE TITLE
dmq_usrloc replication and max_contacts (Kamailio v4.3.1)

### ISSUE THREAD

**Issue by 00Asgaroth00** [kamailio/kamailio#265]
This is a snip from the user's mailing list, I'm just adding it to the issue tracker, as it is yet to be confirmed as a bug, only here for tracking pruporses:

```
I have a situation where I have 2 devices registering with the same AOR, I have the registrar module's max_contacts parameter set to 1 and I use the 0x04 flag on the save function.

When I use dmq_usrloc for replication, I can see 2 contacts registered for the AOR on the "client" nodes whereas the node where the actual registration took place only has 1 contact for the AOR. 
```

```
It seems to me like another bug, although again I'm not familiar with the module so can't be sure without looking that it is not intended behaviour.

I plan to look later this week when I have some time but in the meantime, you can send me the examples directly if you like.
```

**Comment by charlesrchance** [comment]
Hi,

Can you try with https://github.com/kamailio/kamailio/commit/edc25d7373f9560d09a35640ab19741f19b97040, and confirm whether you still observe the same behaviour?

Also make sure max_contacts is set the same on all nodes.

Cheers,
Charles

**Comment by 00Asgaroth00** [comment]
Hi,

Thanks, I will try this out today and get back to you.

**Comment by 00Asgaroth00** [comment]
Hi,

Do you want to keep this issue open for the save flag 0x04 replace action in dmq_usrloc or do you want to close this one and open a new one for the replace action.

FYI, for anyone else looking at this bug report, the particular issue I was experiencing was resolved by either not specifying a flag to save() or using the 0x01 flag and ensuring max_contacts was set properly.

**Comment by kamailio-sync** [comment]
I'm happy to leave it open since the issue is still there if overwriting
contacts (that is, passing 0x04 flag to registrar save function).

On 11 August 2015 at 23:16, 00Asgaroth00 <notifications@github.com> wrote:

> Hi,
>
> Do you want to keep this issue open for the save flag 0x04 replace action
> in dmq_usrloc or do you want to close this one and open a new one for the
> replace action.
>
> FYI, for anyone else looking at this bug report, the particular issue I
> was experiencing was resolved by either not specifying a flag to save() or
> using the 0x01 flag and ensuring max_contacts was set properly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kamailio/kamailio/issues/265#issuecomment-130093889>.
>
> _______________________________________________
> sr-dev mailing list
> sr-dev@lists.sip-router.org
> http://lists.sip-router.org/cgi-bin/mailman/listinfo/sr-dev
>
>


-- 
*Charles Chance*
Managing Director

t. 0121 285 4400    m. 07932 063 891

-- 
*** We're rebranding! Learn more here 
<http://www.sipcentric.com/2015/07/were-rebranding/> ***

www.sipcentric.com

Follow us on twitter @sipcentric <http://twitter.com/sipcentric>

Sipcentric Ltd. Company registered in England & Wales no. 7365592. Registered 
office: Faraday Wharf, Innovation Birmingham Campus, Holt Street, 
Birmingham Science Park, Birmingham B7 4BB.

**Comment by charlesrchance** [comment]
I'm happy to leave it open since the issue is still there if overwriting contacts (that is, passing 0x04 flag to registrar save function).

**Comment by charlesrchance** [comment]
Just looking into this now but I am struggling to reproduce the issue - can you confirm you are still seeing it with the 0x04 flag on save() and that all instances are running the most up-to-date version (with delete replication)?

**Comment by 00Asgaroth00** [comment]
I will re-enable the 0x04 flag shortly and get back to you with findings.

**Comment by 00Asgaroth00** [comment]
Hi, I have re-enabled the 0x04 flag now for a while, and I don't see the original behaviour anymore, 0x04 seems to be replacing the contact properly now.

I will leave it running like this for a while and see if I see it crop up again.

**Comment by miconda** [comment]
Closing to keep the tracker with only active issues. Re-open if it pops up again.

**Comment by gbour** [comment]
Hello,

I can reproduce the issue, with kamailio 4.4.6+jessie from kamailio debian repository:
* 0x04 flag is set on save()
* old contacts are deleted on the server receiving the REGISTER message
* old contacts are not deleted on servers being notified via DMQ




server1 (REGISTER message):
> DEBUG: usrloc [ucontact.c:1692]: update_ucontact(): exists callback for type= UL_CONTACT_UPDATE
> DEBUG: usrloc [ul_callback.h:84]: run_ul_callbacks(): contact=0x7f0096e0b548, callback type 2/15, id 0 entered
> DEBUG: dmq_usrloc [usrloc_sync.c:578]: dmq_ul_cb_contact(): Callback from usrloc with type=2
> DEBUG: dmq_usrloc [usrloc_sync.c:548]: usrloc_dmq_send_contact(): sending serialized data {"action":1,"aor":"+33564093848","ruid":"uloc-5a86b8c5-31e0-2","c":"sip:+33564093848@xxx:41502;ob","received":"","path":"","callid":"ntoWjs3R3WpP9Z5rsi7Npmr2rRGKstls","user_agent":"CSipSimple_porridge-23/r2457","instance":"","expires":1518779539,"cseq":55952,"flags":0,"cflags":0,"q":-1,"last_modified":1518778639,"methods":8159,"reg_id":0}
> DEBUG: dmq_usrloc [usrloc_sync.c:299]: usrloc_dmq_send(): sending dmq broadcast...

server2 (DMQ recipient):
> DEBUG: dmq_usrloc [usrloc_sync.c:327]: usrloc_dmq_handle_msg(): dmq message received from sip:usrloc@172.16.67.15:5060
> DEBUG: dmq_usrloc [usrloc_sync.c:429]: usrloc_dmq_handle_msg(): Received DMQ_UPDATE. Update contact info...
> DEBUG: dmq_usrloc [usrloc_sync.c:64]: add_contact(): aor: +33564093848
> DEBUG: dmq_usrloc [usrloc_sync.c:65]: add_contact(): ci->ruid: uloc-5a86b8c5-31e0-2
> DEBUG: dmq_usrloc [usrloc_sync.c:66]: add_contact(): aorhash: -1799456359
> DEBUG: dmq_usrloc [usrloc_sync.c:72]: add_contact(): Found contact
> DEBUG: usrloc [ucontact.c:1692]: update_ucontact(): exists callback for type= UL_CONTACT_UPDATE
> DEBUG: usrloc [ul_callback.h:84]: run_ul_callbacks(): contact=0x7f3900243bd0, callback type 2/15, id 0 entered
> DEBUG: dmq_usrloc [usrloc_sync.c:578]: dmq_ul_cb_contact(): Callback from usrloc with type=2
> DEBUG: dmq_usrloc [usrloc_sync.c:600]: dmq_ul_cb_contact(): Contact received from DMQ... skip
> DEBUG: usrloc [ucontact.c:1004]: db_update_ucontact_ruid(): ruid:uloc-5a86b8c5-31e0-2
> DEBUG: usrloc [ucontact.c:1133]: db_update_ucontact_ruid(): contact:sip:+33564093848@xxx:41502;ob
> DEBUG: dmq_usrloc [usrloc_sync.c:74]: add_contact(): Release record
> DEBUG: dmq_usrloc [usrloc_sync.c:76]: add_contact(): Unlock udomain


the recipient receive an UPDATE message only.
according to usrloc_sync.c:usrloc_dmq_handle_msg(), UPDATE message add the new contact only (execute add_contact()), but the other one is not deleted

and there is no DMQ_RM message generated from the emitter

**Comment by miconda** [comment]
Open a new issue, the item here is for another version. Thanks!
